import { LogDetailsModal } from "@/components/logs/LogDetailsModal";
import { LogFilter } from "@/components/logs/LogFilter";
import { LogItem, LogLevel } from "@/components/logs/LogItem";
import { useTheme } from "@/contexts/ThemeContext";
import { Ionicons } from "@expo/vector-icons";
import React, { useMemo, useState } from "react";
import {
  Alert,
  Platform,
  RefreshControl,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
  View,
} from "react-native";

export type LogType = {
  id: string;
  timestamp: Date;
  level: LogLevel;
  message: string;
  source: string;
  details?: Record<string, any>;
  userId?: string;
  deviceInfo?: {
    platform: string;
    version: string;
  };
};

export default function LogsScreen() {
  const theme = useTheme();
  const [logs, setLogs] = useState<LogType[]>([
    // {
    //   id: "1",
    //   timestamp: new Date("2024-01-15T10:30:00"),
    //   level: "info",
    //   message: "Aplicativo iniciado com sucesso",
    //   source: "AppStartup",
    //   details: { version: "1.2.3", build: "456" },
    //   deviceInfo: {
    //     platform: Platform.OS,
    //     version: Platform.Version.toString(),
    //   },
    // },
  ]);

  const [searchQuery, setSearchQuery] = useState("");
  const [selectedLevel, setSelectedLevel] = useState<LogLevel | "all">("all");
  const [refreshing, setRefreshing] = useState(false);
  const [selectedLog, setSelectedLog] = useState<LogType | null>(null);
  const [showDetailsModal, setShowDetailsModal] = useState(false);

  const filteredLogs = useMemo(() => {
    return logs.filter((log) => {
      if (selectedLevel !== "all" && log.level !== selectedLevel) {
        return false;
      }

      if (searchQuery.trim() !== "") {
        const query = searchQuery.toLowerCase();
        return (
          log.message.toLowerCase().includes(query) ||
          log.source.toLowerCase().includes(query) ||
          (log.details &&
            JSON.stringify(log.details).toLowerCase().includes(query))
        );
      }

      return true;
    });
  }, [logs, searchQuery, selectedLevel]);

  // Estatísticas
  const stats = useMemo(() => {
    return {
      total: logs.length,
      info: logs.filter((log) => log.level === "info").length,
      warn: logs.filter((log) => log.level === "warn").length,
      error: logs.filter((log) => log.level === "error").length,
      debug: logs.filter((log) => log.level === "debug").length,
    };
  }, [logs]);

  const handleRefresh = () => {
    setRefreshing(true);
    // Simular carregamento de novos logs
    setTimeout(() => {
      const newLog: LogType = {
        id: Date.now().toString(),
        timestamp: new Date(),
        level: ["info", "warn", "error", "debug"][
          Math.floor(Math.random() * 4)
        ] as LogLevel,
        message: `Log atualizado em ${new Date().toLocaleTimeString()}`,
        source: "System",
        details: { autoGenerated: true },
      };
      setLogs((prev) => [newLog, ...prev]);
      setRefreshing(false);
    }, 1000);
  };

  const handleClearLogs = () => {
    Alert.alert(
      "Limpar Logs",
      "Tem certeza que deseja limpar todos os logs? Esta ação não pode ser desfeita.",
      [
        { text: "Cancelar", style: "cancel" },
        {
          text: "Limpar",
          style: "destructive",
          onPress: () => {
            setLogs([]);
            Alert.alert("Sucesso", "Todos os logs foram limpos.");
          },
        },
      ]
    );
  };

  const handleExportLogs = () => {
    Alert.alert("Exportar Logs", "Escolha o formato de exportação:", [
      { text: "Cancelar", style: "cancel" },
      {
        text: "JSON",
        onPress: () => {
          const logData = JSON.stringify(logs, null, 2);
          Alert.alert(
            "Logs Exportados",
            `Dados em JSON prontos para uso:\n\nTotal: ${logs.length} registros`
          );
          // Aqui você pode implementar o compartilhamento real
        },
      },
      {
        text: "Texto",
        onPress: () => {
          const logText = logs
            .map(
              (log) =>
                `[${log.timestamp.toISOString()}] ${log.level.toUpperCase()}: ${log.message} (${log.source})`
            )
            .join("\n");
          Alert.alert(
            "Logs Exportados",
            `Dados em texto prontos para uso:\n\nTotal: ${logs.length} registros`
          );
          // Aqui você pode implementar o compartilhamento real
        },
      },
    ]);
  };

  const handleLogPress = (log: LogType) => {
    setSelectedLog(log);
    setShowDetailsModal(true);
  };

  const styles = useMemo(
    () =>
      StyleSheet.create({
        container: {
          flex: 1,
          backgroundColor: theme.theme.background,
          paddingTop: Platform.OS === "ios" ? 16 : 20,
        },
        header: {
          paddingHorizontal: 20,
          paddingTop: 20,
          paddingBottom: 15,
          backgroundColor: theme.theme.background,
          borderBottomWidth: 1,
          borderBottomColor: theme.theme.border,
        },
        headerTitle: {
          fontSize: 24,
          fontWeight: "bold",
          color: theme.theme.text,
          marginBottom: 10,
        },
        statsContainer: {
          flexDirection: "row",
          justifyContent: "space-between",
          marginBottom: 15,
        },
        statCard: {
          flex: 1,
          alignItems: "center",
          padding: 12,
          borderRadius: 12,
          marginHorizontal: 4,
        },
        statCount: {
          fontSize: 20,
          fontWeight: "bold",
          marginBottom: 4,
        },
        statLabel: {
          fontSize: 12,
          opacity: 0.8,
        },
        searchContainer: {
          flexDirection: "row",
          alignItems: "center",
          backgroundColor: theme.theme.surface,
          borderRadius: 12,
          paddingHorizontal: 15,
          paddingVertical: 10,
        },
        searchInput: {
          flex: 1,
          marginLeft: 10,
          color: theme.theme.text,
          fontSize: 16,
        },
        actionsContainer: {
          flexDirection: "row",
          paddingHorizontal: 20,
          paddingVertical: 15,
          backgroundColor: theme.theme.background,
          borderBottomWidth: 1,
          borderBottomColor: theme.theme.border,
        },
        actionButton: {
          flexDirection: "row",
          alignItems: "center",
          backgroundColor: theme.theme.surface,
          paddingHorizontal: 16,
          paddingVertical: 10,
          borderRadius: 12,
          marginRight: 10,
        },
        actionText: {
          marginLeft: 6,
          color: theme.theme.text,
          fontSize: 14,
          fontWeight: "500",
        },
        content: {
          flex: 1,
          paddingHorizontal: 20,
        },
        listHeader: {
          flexDirection: "row",
          justifyContent: "space-between",
          alignItems: "center",
          marginTop: 15,
          marginBottom: 10,
        },
        listTitle: {
          fontSize: 18,
          fontWeight: "600",
          color: theme.theme.text,
        },
        logCount: {
          fontSize: 14,
          color: theme.theme.textSecondary,
        },
        emptyContainer: {
          flex: 1,
          justifyContent: "center",
          alignItems: "center",
          paddingVertical: 50,
        },
        emptyIcon: {
          marginBottom: 20,
        },
        emptyText: {
          fontSize: 16,
          color: theme.theme.textSecondary,
          textAlign: "center",
          marginTop: 10,
        },
      }),
    [theme]
  );

  return (
    <View style={styles.container}>
      {/* Header e Estatísticas */}
      <View style={styles.header}>
        <Text style={styles.headerTitle}>Logs do Sistema</Text>

        <View style={styles.statsContainer}>
          <View
            style={[
              styles.statCard,
              { backgroundColor: theme.theme.info + "20" },
            ]}
          >
            <Text style={[styles.statCount, { color: theme.theme.info }]}>
              {stats.total}
            </Text>
            <Text
              style={[styles.statLabel, { color: theme.theme.textSecondary }]}
            >
              Total
            </Text>
          </View>
          <View
            style={[
              styles.statCard,
              { backgroundColor: theme.theme.success + "20" },
            ]}
          >
            <Text style={[styles.statCount, { color: theme.theme.success }]}>
              {stats.info}
            </Text>
            <Text
              style={[styles.statLabel, { color: theme.theme.textSecondary }]}
            >
              Info
            </Text>
          </View>
          <View
            style={[
              styles.statCard,
              { backgroundColor: theme.theme.warning + "20" },
            ]}
          >
            <Text style={[styles.statCount, { color: theme.theme.warning }]}>
              {stats.warn}
            </Text>
            <Text
              style={[styles.statLabel, { color: theme.theme.textSecondary }]}
            >
              Warn
            </Text>
          </View>
          <View
            style={[
              styles.statCard,
              { backgroundColor: theme.theme.error + "20" },
            ]}
          >
            <Text style={[styles.statCount, { color: theme.theme.error }]}>
              {stats.error}
            </Text>
            <Text
              style={[styles.statLabel, { color: theme.theme.textSecondary }]}
            >
              Error
            </Text>
          </View>
        </View>

        {/* Barra de pesquisa */}
        <View style={styles.searchContainer}>
          <Ionicons name="search" size={20} color={theme.theme.textSecondary} />
          <TextInput
            style={styles.searchInput}
            placeholder="Buscar logs..."
            placeholderTextColor={theme.theme.textSecondary}
            value={searchQuery}
            onChangeText={setSearchQuery}
            clearButtonMode="while-editing"
          />
        </View>
      </View>

      {/* Filtros */}
      <LogFilter
        selectedLevel={selectedLevel}
        onSelectLevel={setSelectedLevel}
      />

      {/* Ações */}
      <View style={styles.actionsContainer}>
        <TouchableOpacity style={styles.actionButton} onPress={handleRefresh}>
          <Ionicons name="refresh" size={18} color={theme.theme.primary} />
          <Text style={styles.actionText}>Atualizar</Text>
        </TouchableOpacity>

        <TouchableOpacity
          style={styles.actionButton}
          onPress={handleExportLogs}
        >
          <Ionicons
            name="download-outline"
            size={18}
            color={theme.theme.primary}
          />
          <Text style={styles.actionText}>Exportar</Text>
        </TouchableOpacity>

        <TouchableOpacity
          style={[
            styles.actionButton,
            { backgroundColor: theme.theme.error + "20" },
          ]}
          onPress={handleClearLogs}
        >
          <Ionicons name="trash-outline" size={18} color={theme.theme.error} />
          <Text style={[styles.actionText, { color: theme.theme.error }]}>
            Limpar
          </Text>
        </TouchableOpacity>
      </View>

      {/* Lista de Logs */}
      <View style={styles.content}>
        <View style={styles.listHeader}>
          <Text style={styles.listTitle}>Registros</Text>
          <Text style={styles.logCount}>
            {filteredLogs.length} de {logs.length} logs
          </Text>
        </View>

        {filteredLogs.length === 0 ? (
          <View style={styles.emptyContainer}>
            <Ionicons
              name="document-text-outline"
              size={64}
              color={theme.theme.textSecondary}
              style={styles.emptyIcon}
            />
            <Text style={styles.emptyText}>
              {searchQuery || selectedLevel !== "all"
                ? "Nenhum log encontrado para os filtros atuais"
                : "Nenhum log disponível"}
            </Text>
          </View>
        ) : (
          <ScrollView
            showsVerticalScrollIndicator={false}
            refreshControl={
              <RefreshControl
                refreshing={refreshing}
                onRefresh={handleRefresh}
                colors={[theme.theme.primary]}
                tintColor={theme.theme.primary}
              />
            }
          >
            {filteredLogs.map((log) => (
              <TouchableOpacity
                key={log.id}
                onPress={() => handleLogPress(log)}
                activeOpacity={0.7}
              >
                <LogItem log={log} />
              </TouchableOpacity>
            ))}
          </ScrollView>
        )}
      </View>

      {/* Modal de Detalhes */}
      <LogDetailsModal
        visible={showDetailsModal}
        log={selectedLog}
        onClose={() => setShowDetailsModal(false)}
      />
    </View>
  );
}
